version: '3'
services:

# PHP service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:7.3-fpm
        container_name: php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
# NGINX
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "7777:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
# MySQL
    db:
        image: mysql:5.7.24
        container_name: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        restart: unless-stopped
        tty: true
        ports:
            - "7776:3306"
        environment:
            MYSQL_DATABASE: webinar_laravel
            MYSQL_USER: webinar_laravel
            MYSQL_PASSWORD: webinar_laravel
            MYSQL_ROOT_PASSWORD: webinar_laravel
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "7778:80"