version: "3"
services:
    # PHP service
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:7.3-fpm
        container_name: php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./src/:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        links:
            - db
    # NGINX
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "7777:80"
        volumes:
            - ./src/:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app
    # MySQL
    db:
        image: mysql:5.7.24
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "6033:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: okbhmao
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
