version: "3"
services:
    # PHP service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:7.3-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        links:
            - db
    # NGINX
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "7777:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - app-network
    # MySQL
    db:
        image: mysql:5.7.24
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "7776:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_db
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf
        networks:
            - app-network
    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db
        ports:
            - "7778:80"
        links:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
