version: "3"
services:
    # PHP service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:7.4-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./src/:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        links:
            - db
    # NGINX
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "7777:80"
        volumes:
            - ./src/:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app
    # MySQL
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Aa12345
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        networks:
            - app-network
    # phpMyAdmin
    pma:
        image: phpmyadmin
        container_name: pma
        restart: unless-stopped
        ports:
            - "7778:80"
        networks:
            - app-network
        links:
            - db
networks:
    app-network:
        driver: bridge
